config/routes.rb
TeddArcuri::Application.routes.draw do
  get "pages/home"
  get "pages/about"
  get "pages/contact"

  get "login", :to => "user_sessions#new"

  root 'pages#home'

      resources :projects
      resources :users
      resources :user_sessions

end

app/models/asset.rb
class Asset < ActiveRecord::Base

	belongs_to :project

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/project.rb
class Project < ActiveRecord::Base

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	has_many :assets, dependent: :destroy
	accepts_nested_attributes_for :assets, allow_destroy: :true

	scope :ordered, -> {
		order("projects.order ASC")
	}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :username, presence: true,
						 uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
  	@projects = Project.ordered
  end

  def show
  	@project = Project.find(params[:id])
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

  def new
  	@project = Project.new(order: 100)
    5.times {@project.assets.build}
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

  def create
  	@project = Project.new(project_params)

  	if @project.save
      flash[:success] = "You successfully created #{@project.name}!"
  		redirect_to(:action => "index")
  	else
  		render('new')
  	end
  end

  def edit
  	@project = Project.find(params[:id])
    5.times {@project.assets.build}
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

  def update
  	@project = Project.find(params[:id])

  	if @project.update_attributes(project_params)
      flash[:success] = "You successfully updated the project: #{@project.name}!"
  		redirect_to(:action => "index")
  	else
  		render('edit')
  	end
  end

  def destroy
    project = Project.find(params[:id])
    project.destroy
    flash[:success] = "You successfully deleted the project: #{project.name}"
    redirect_to(:action => "index")
  end

  private	
	  def project_params
	  	  params.require(:project).permit(:name, :description, :kind, :order, :myrole, :features, :technologies, :siteurl, :image, :remove_image, :assets_attributes => [:image, :id])
	  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	user = User.find_by(username: params[:username])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		flash[:success] = "Welcome, #{user.username}. You have successfully signed in."
  		redirect_to projects_path
  	else
  		render action: 'new'
  	end
  end

  def destroy
  	session[:user_id] = nil
  	flash[:success] = "You have been logged out, sir."
  	redirect_to projects_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Thanks for signing up " + @user.username + "!"
  		redirect_to(:controller => "pages", :action => "home")
  	else
  		render('new')
  	end
  end

  private	
	  def user_params
	  	  params.require(:user).permit(:username, :password, :password_confirmation)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def logged_in
		session[:user_id]
	end

	def current_user_id
		session[:user_id]
	end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_contact.html.erb
<div class="overlay contact-overlay">
	<div class="modal">
	<div class="close-overlay"><h3>X</h3></div>
		<h1>Let's get in touch.</h1>
		<p>Whether you're interested in hiring me for my services or simply want to chat programming/design, I'd love to hear from you. Feel free to call, text, email, whatever. Please just make sure to let me know who you are!</p>
		<br />
		<h3>(719)440-4732</h3><br>
		<h3>tedd.arcuri@gmail.com</h3><br>
		<ul class="social">
			<a target="_blank" href="https://github.com/teddarcuri/"><li class="social-icon github"></li></a>
			<a target="_blank" href="https://www.linkedin.com/pub/tedd-arcuri/76/7a/252"><li class="social-icon linkedin"></li></a>
			<a target="_blank" href="https://twitter.com/TeddArcuri"><li class="social-icon twitter"></li></a>
		</ul>
	</div>
</div>

app/views/layouts/_loading.html.erb
<div class="overlay loading-overlay">
	
</div>

app/views/layouts/_login.html.erb
<div class="overlay login-overlay">
	<div class="modal">
		<div class="close-overlay"><h3>X</h3></div>

		<h1>Log In</h1>
		<br />
		<center><p>I built this site on top of the Rails framework and implemented a custom personal CMS. I use this to manage my projects and more. Of course I have restriced access, but I'd love to show you around if you're curious, just shoot me an email at tedd.arcuri@gmail.com. In fact, I left the login button on the site to, if anything, spark some curiosity ;)</p></center>
		<br>
		<%= form_tag user_sessions_path do %>

			<%= label_tag :username %><br />
			<%= text_field_tag :username, params[:username] %><br />

			<%= label_tag :password %><br />
			<%= password_field_tag :password %><br />

			<%= submit_tag "Log In", class: "login-btn" %>

		<% end %>	
	</div>
</div>

app/views/layouts/_nav.html.erb
<nav>
	<%= link_to " ", root_path, id: "logo" %>
	<div class="nav-container">
		<div class="mobile-nav-close">X</div>
		<ul class="navigation">
			<li><%= link_to "Me, The Person", {controller: "pages", action: "about"} %></li>
			<li><%= link_to "My Work", projects_path %></li>
			<li class="contact-modal-toggle"><a>Contact Me</a></li>
		</ul>

		<ul class="social">
			<a target="_blank" href="https://github.com/teddarcuri/"><li class="social-icon github"></li></a>
			<a target="_blank" href="https://www.linkedin.com/pub/tedd-arcuri/76/7a/252"><li class="social-icon linkedin"></li></a>
			<a target="_blank" href="https://twitter.com/TeddArcuri"><li class="social-icon twitter"></li></a>
			<% if !logged_in %>
			<li class="login-modal-toggle social-icon login "></li>
			<% else %>
			<li class="social-icon logout"><%= link_to "", user_session_path(id: current_user_id), method: :delete %></li>
			<% end %>
		</ul>
	</div>

	<div class="mobile-nav-open">
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tedd Arcuri | Web Designer/Developer</title>
  <%= favicon_link_tag 'favicon.ico'%>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <!-- Typekit Fonts -->
  <script type="text/javascript" src="//use.typekit.net/iiw2cmb.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

  <!-- Viewport stuff -->
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" /> 

  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/loading' %>

<% if !flash[:success].blank? %>
	<div class="notice success">
		<%= flash[:success] %>
	</div>	
<% end %>

<%= render 'layouts/nav' %>

<%= yield %>

<%= render 'layouts/contact' %>
<%= render 'layouts/login' %>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/pages/about.html.erb
<div class="left-panel">
		<div class="loading-overlay"></div>
</div>

<div class="right-panel">
	<h1>I Design. I Code. I Solve Problems.</h1>

	<div class="charts">
		<div class="chart-wrap">
			<div class="chart" data-percent="100" data-scale-color="#ffffff"><span>HTML</span></div>

			<div class="chart" data-percent="100" data-scale-color="#ffffff"><span>CSS</span></div>

			<div class="chart" data-percent="50" data-scale-color="#ffffff"><span>Ruby</span></div>

			<div class="chart" data-percent="75" data-scale-color="#ffffff"><span>PHP</span></div>

			<div class="chart" data-percent="75" data-scale-color="#ffffff"><span>Javascript</span></div>

			<div class="chart" data-percent="75" data-scale-color="#ffffff"><span>Photoshop</span></div>

			<div class="chart" data-percent="100" data-scale-color="#ffffff"><span>Illustrator</span></div>

			<div class="chart" data-percent="25" data-scale-color="#ffffff"><span>InDesign</span></div>
		</div>

	</div>

	<section class="about">
		<h2>Technologies</h2>
		<div>
			<h3>Front End</h3>
			<hr>
			<ul>
				<li>HTML (ERB, Haml)</li>
				<li>CSS ( Sass = &hearts; )</li>
				<li>Javascript (jQuery, Coffeescript, Ajax)</li>
			</ul>
			<h3>Back End</h3>
			<hr>	
			<ul>
				<li>PHP (Wordpress, Joomla)</li>
				<li>Ruby (Rails)</li>
				<li>Databases (MySQL, Postgres, SQLite3)</li>
				<li>Servers (Apache)</li>
			</ul>
			<h3>Dev/Design Tools</h3>
			<hr>
				<ul>
					<li>Git (Github)</li>
					<li>Command Line</li>
					<li>Photoshop</li>
					<li>Illustrator</li>
					<li>InDesign</li>
				</ul>
			<h3>Concepts</h3>
			<hr>
				<ul>
					<li>MVC</li>
					<li>OOP</li>
					<li>Design Fundamentals</li>
					<li>Color Theory</li>
				</ul>
			<h3>The Pipeline (Currently learning)</h3>
			<hr>
				<ul>
					<li>Laravel</li>
					<li>Ember.js</li>
				</ul>
			<hr>
		</div>
	</section>

	<section class="about">
		<h2>About Me</h2>
		<div>
			<p>
			I am a web designer/developer with a passion for creating harmony between purposeful design and objective functionality. I work to make a seemless transition between sensable user interfaces and tight-knit back end "business logic". Each day, I try to get better at bridging the gap between the "front-end" and "back-end" worlds in order to create a harmonious, synchronized experience for this amazing platform we call the web. 
			<br>
			<br>
			I also have a versatile design skill set. I design/code all of my webapps/sites and have an exstensive background in general graphic/print design as well. I can do logos, illustrations (both cartoon and realistic), among other things. I really do have a passion for the interactive though and &hearts; UI/UX design.
			</p>
		</div>
	</section>

	<section class="about">
		<h2>Education</h2>
		<div>
			<ul>
				<li>AA in Digital Media Design - Colorado Technical University - June 2013</li>
				<li>HS - Colorado Springs Early Colleges - Class of 2009</li>
			</ul>
		</div>
	</section>

	<section class="about">
		<h2>Interests/Hobbies</h2>
		<div>
			<ul>
				<li>Huge hockey fan. Go Avs!</li>
				<li>Camping - Hiking - Biking</li>
				<li>Cooking</li>
				<li>Botany - Bird watching - Anything biology related really</li>
				<li>Programming - Design</li>
			</ul>
		</div>
	</section>
</div>

app/views/pages/home.html.erb
<!-- Hello, My Name Is -->
<div class="hello">
	<h1 class="headline"></h1>
	<div class="bottom-portion">
		<div class="name-container">
			<h1 class="name">T<%= image_tag("me-with-e.png", class: "me-with-e") %>dd</h1>
		</div>
		<div class="call-to-action">
			<center>
			<h2 class="typed">I Design. I Code. I Solve Problems.</h2>
			<%= link_to "A Little About Me", pages_about_path, class: "button" %>
			<%= link_to "See My Work", projects_path, class: "button" %>
			</center>
		</div>
	</div>
</div> <!-- End Hello -->

app/views/projects/_edit_showcase.html.erb
<div class="showcase admin-showcase edit-showcase showcase-hide">
	
</div>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :multipart => true } do |f| %>

<%= tinymce theme: "modern"%>

	<h2>Name</h2>
	<%= f.text_field :name %>

	<div class="inset">
		<h2>Preview Image</h2>
		<% if @project.image? %>
		<br>
			<%= image_tag @project.image.url(:medium) %>
		<% end %>

		<%= f.file_field :image %>
	</div>

	<% if !@project.new_record? %>
		<div class="inset">
			<h3>Existing Gallery Images</h3>

			<div class="slideshow">
				<%= f.fields_for :assets do |asset| %>
				<% unless asset.object.new_record? %>
					<div>
						<%= link_to( image_tag( asset.object.image.url(:medium)), asset.object.image.url(:original)) %>
					</div>
				<% end %>
			<% end %>
			</div>
			
		</div>
	<% end %>
	<div class="inset">
		<h2>Add Gallery Images</h2>
		<%= f.fields_for :assets do |asset| %>

			<% if asset.object.new_record? %>
				<%= asset.file_field :image %> <hr>
			<% end %>

		<% end %>
	</div>

	<div class="left-input">
		<h2>Kind</h2>
		<%= f.select(:kind, options_for_select([['Logo', 'logo'], ['Web', 'web'], ['Illustration', 'illustration']]) ) %>
	</div>
	
	<div class="right-input">
		<h2>Order</h2>
		<%= f.number_field :order %><br />
	</div>

	<div class="left-input">
		<h2>Site Url</h2>
		<%= f.text_field :siteurl %>
	</div>
	
	<div class="right-input">
		<h2>My Role</h2>
		<%= f.text_field :myrole %>
	</div>

	<h2>Description</h2>
	<%= f.text_area :description, class: "tinymce" %><br />

	<h2>Key Features</h2>
	<%= f.text_area :features, class: "tinymce" %>

	<h2>Technolgies</h2>
	<%= f.text_area :technologies, class: "tinymce" %>
	

	<%= f.submit( :class => "login-btn") %>

<% end %>

app/views/projects/_new_showcase.html.erb
<div class="showcase admin-showcase new-showcase showcase-hide">

	
</div>	

app/views/projects/_project_showcase.html.erb
<!-- The project showcase -->
<div class="showcase project-showcase showcase-hide">

</div>

app/views/projects/edit.html.erb
<div class="container">
	<h1>Update <%= @project.name %></h1>

	<%= render 'form' %>

	<div class="showcase-close"><h3>X</h3></div>
</div>

app/views/projects/index.html.erb
<!-- The main container | App -->
<div class="container">
	<!-- Control Bar | Sort, Admin CRUD, etc. -->
	<div class="control-bar">
		<% if !logged_in %>
			<h1>My Work <span class="mobile">Swipe the photos <%= image_tag("swipe.svg") %> left and right to see more.</span><span>Click the <%= image_tag("eye.svg") %> icon to view large images and project details.</span></h1>
		<% else %>
			<h1>Admin Panel</h1>
		<% end %>
		<div class="controls">
			<% if logged_in %>
				<!-- If user is logged in -->
				<a class="button new-showcase-toggle">Create A New Project</a>
				<%= link_to "Logout", user_session_path(id: current_user_id), method: :delete, class: "button" %>
			<% else %>
				<a data-filter="*" class="button">View All</a>
				<a data-filter=".web" class="button">Web</a>
				<a data-filter=".logo" class="button">Logo</a>
				<a data-filter=".illustration" class="button">Illustration</a>
			<% end %>
		</div>
	</div> 

	<!-- The Projects Container -->
	<div class="projects-container">
		<% @projects.each do |project| %>
		<div class="project-shell <%= project.kind.downcase %>">
			<div id="<%= dom_id(project) %>" class="project">
				<div class="project-photo" style="background: url() no-repeat center center">
					<div class="slideshow">
						<% if project.assets %>
						<% project.assets.each do |asset| %>
							<div>
								<%= image_tag asset.image.url(:original) %>
							</div>
						<% end %>
					<% end %>
					</div>

					<% if logged_in %>
					<div class="project-order">
						<%= project.order %>
					</div>
					<div class="crud-tools">
						<a class="edit-showcase-toggle">Edit</a>
						<%= link_to "", project_path(:id => project.id), method: :delete, :class => "delete-project" %>
					</div>
					<% end %>

					<div class="project-info">
						<h2 class="project-name">
							<%= project.name %>
						</h2>
						<a class="project-kind"><%= project.kind %></a>
					</div>
				</div>

				<div class="toolbar">
					<a class="view-project"></a>
					<a><%= project.name %></a>
				</div>

			</div>
		</div>
		<% end %>
	</div>
</div>

<%= render 'projects/project_showcase' %>
	
<% if logged_in %>
	<!-- Admin Showcases -->
	<%= render 'projects/new_showcase' %>
	<%= render 'projects/edit_showcase' %>
<% end %>

app/views/projects/new.html.erb
<div class="container">
	<h1>New Project</h1>

	<%= render 'form' %>

	<div class="showcase-close"><h3>X</h3></div>
</div>

app/views/projects/show.html.erb
<div class="gallery">
	<div class="showcase-close"><h3>X</h3></div>
	<div class="slideshow">
		<% if @project.assets %>
			<% @project.assets.each do |asset| %>
				<div>
					<%= image_tag asset.image.url(:original) %>
				</div>
			<% end %>
		<% end %>
	</div>
</div>

<div class="sidebar">
	<h1><%= @project.name %></h1>
	<h4><%= @project.kind %></h4>
	<div class="myrole"><%= @project.myrole %></div> 

	<% if @project.description? %>
	<section class="about">
		<h2>Project Overview</h2>
		<div>
			<p><%= raw @project.description %></p>
		</div>
	</section>
	<% end %>	

	<% if @project.features? %>
	<section class="about">
		<h2>Key Features</h2>
		<div>
			<p><%= raw @project.features %></p>
		</div>
	</section>
	<% end %>	

	<% if @project.technologies? %>
	<section class="about">
		<h2>Technologies</h2>
		<div>
			<p><%= raw @project.technologies %></p>
		</div>
	</section>
	<% end %>

	<% if @project.siteurl? %>
		<center>
			<a target="_blank" href="<%= @project.siteurl %>" class="button-lrg">View the site</a>
		</center>
	<% end %>
</div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="container form">
	<h1>Log In</h1>
	<br />
	<p>I use this portal to manage my site. I built this site on top of the Rails framework and implemeneted a custom personal CMS. I'd love to show you around if you're curious, just shoot me an email at tedd.arcuri@gmail.com </p>
	<hr>
	<%= form_tag user_sessions_path do %>

		<%= label_tag :username %><br />
		<%= text_field_tag :username, params[:username] %><br />

		<%= label_tag :password %><br />
		<%= password_field_tag :password %><br />

		<%= submit_tag "Log In", class: "login-btn" %>

	<% end %>	
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<%= user.username %>
<% end %>

app/views/users/new.html.erb
<div class="container">
	<h1>New User</h1>

	<%= form_for @user, url: users_path do |f| %>
		<%= f.label :username %><br />
		<%= f.text_field :username %><br />
		<%= f.label :password %><br />
		<%= f.text_field :password %><br />
		<%= f.label :password_confirmation %><br />
		<%= f.text_field :password_confirmation %><br />
		

		<%= f.submit("Create a user") %>

	<% end %>
</div>	
	

app/views/users/show.html.erb
<%= @user.username %>
<%= @user.password %>